### ISSUE TITLE
安卓火狐，我用浏览器自带的“请求桌面版本”得到的桌面版网页，和通过第三方扩展修改UA得到的桌面版网页，两种情况配合这个脚本出现了不同的显示效果

### ISSUE THREAD

**Issue by mo-han** [hceasy/simpleZhiHu#1]
这是用安卓火狐自带的“请求桌面版网页”的效果：
![S90712-21454992](https://user-images.githubusercontent.com/9916948/61134509-5369e300-a4f2-11e9-9057-9b4c87ae6a05.jpg)
这是用改了UserAgent后得到的桌面版网页配合脚本运行的效果：
![S90712-21485534](https://user-images.githubusercontent.com/9916948/61134523-582e9700-a4f2-11e9-90f4-b31beb388f6a.jpg)

**Comment by hceasy** [comment]
这个目前没有对移动版进行适配.

**Comment by mo-han** [comment]
勉强还能用，配合切换UA的扩展后效果也还行
