### ISSUE TITLE
建议将赞赏按钮的颜色调淡

### ISSUE THREAD

**Issue by etbox** [hceasy/simpleZhiHu#10]
![image](https://user-images.githubusercontent.com/16815152/96068168-e94aa580-0ecd-11eb-8ce6-13adee2fdb4f.png)
在点赞按钮已经不显眼的情况下，出现一个极其显眼的红色按钮显得很突兀

**Comment by hceasy** [comment]
这个是知乎设计的问题
此类问题不做修复.
严重影响阅读的话可以屏蔽.
