### ISSUE TITLE
[BUG]点击’查看回复‘，有时正常，但有时会瞬间弹出一个正常界面，但又马上被关闭！

### ISSUE THREAD

**Issue by maybe114** [hceasy/simpleZhiHu#14]

**Comment by maybe114** [comment]
并且随后‘查看回复’点击不再生效

**Comment by hceasy** [comment]
有这个情况,知乎更新了之后,不让登录不给滑动看更多信息.就紧急更新把登录界面去掉了.
然后会留下两个遮罩层,导致界面不能点击.
遮罩层CSS和留言回复共用一个类.无法区分做屏蔽.
加了一个计数器,屏蔽过两次之后就不再屏蔽这个.
但有时候页面载入因为网络问题,只载入了一个遮罩,导致第二个点开的查看回复会被当成第二个遮罩屏蔽掉.
正在想办法规避.
