### ISSUE TITLE
页面不显示问题描述

### ISSUE THREAD

**Issue by nnop** [hceasy/simpleZhiHu#3]
先赞一个，让知乎清爽多了!

版本：0.1.14
现象：启用脚本之后，页面不显示问题描述了，只显示回答。
系统是macos，浏览器chrome，`ctrl+alt+shift+Q`快捷键也无效

如：https://www.zhihu.com/question/326431372

![image](https://user-images.githubusercontent.com/23091984/68018207-90412c00-fcd3-11e9-9424-25bb663ef70c.png)

**Comment by hceasy** [comment]
晚点儿我测试下.

**Comment by nnop** [comment]
另外，`sConfig`怎么设置？`localStorage`存储在哪里啊？

抱歉，不懂js

**Comment by nnop** [comment]
咋样了，老哥

**Comment by hceasy** [comment]
已修复.

**Comment by hceasy** [comment]
> 另外，`sConfig`怎么设置？`localStorage`存储在哪里啊？
> 
> 抱歉，不懂js

sConfg是随手打的变量,不需要设置.
localStorage为浏览器本地储存,F12打开调试直接输入按回车就能看到信息.

**Comment by nnop** [comment]
赞👍
