### ISSUE TITLE
还是不够隐蔽啊兄弟，能不能再简洁点？

### ISSUE THREAD

**Issue by MukuroSama** [hceasy/simpleZhiHu#4]
把页面左上角的知乎logo去掉
把点赞点踩的样式去掉，弄成黑白按钮
把标题和正文弄成差不多的字体，去掉标题粗体，字统一调小，乍一看密密麻麻不知道什么东西最好
完全牺牲掉
图片默认不加载，留个小框，让人知道这里是个图，点击后可加载出该图。

**Comment by hceasy** [comment]
可以考虑下.除了最后一项
