### ISSUE TITLE
知乎专栏不能极简

### ISSUE THREAD

**Issue by genglz1983** [hceasy/simpleZhiHu#5]
在知乎专栏页面，脚本不工作。
例如: https://zhuanlan.zhihu.com/p/42944600

**Comment by hceasy** [comment]
说一下需求?

**Comment by genglz1983** [comment]
希望知乎专栏页面也可以和知乎问答页面一样伪装。
第二幅图是知乎专栏的效果。可以看出脚本在该页面没有工作。

![wenda](https://user-images.githubusercontent.com/55374771/78756856-14e45480-79ae-11ea-8fa1-82b1e3b1bf26.JPG)
![zhuanlan](https://user-images.githubusercontent.com/55374771/78756861-16ae1800-79ae-11ea-93a3-3a8dbb4d1084.JPG)

**Comment by willzhqiang** [comment]
刚才也发现这个问题了，在专栏上面不生效。

**Comment by hceasy** [comment]
没适配这个页面暂时...
最近忙疯了..没空看这个.

**Comment by hceasy** [comment]
0.1.20已经修复
