### ISSUE TITLE
希望屏蔽`故事档案局`的内容 ​

### ISSUE THREAD

**Issue by hallkk** [hceasy/simpleZhiHu#6]
如题

**Comment by hceasy** [comment]
贴个图

**Comment by hallkk** [comment]
如何评价知乎的故事档案局账号？
https://www.zhihu.com/question/366636801

每个回答下几乎都是付费内容
![image](https://user-images.githubusercontent.com/1014928/79524325-c95b3600-8092-11ea-89d4-94a4f3312265.png)

@hceasy

**Comment by hallkk** [comment]
或者支持一个类似`黑名单`功能，block掉不想看的人

**Comment by hceasy** [comment]
观察了一段时间,类似的还有知乎盐选.
看了下样式和普通回答没区别.
另外这个属于知乎的收钱入口,不太好做屏蔽.还有广告那些.

**Comment by hallkk** [comment]
了解，谢谢
